INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('654','Banco A.J.Renner S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('246','Banco ABC Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('25','Banco Alfa S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('641','Banco Alvorada S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('213','Banco Arbi S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('19','Banco Azteca do Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('29','Banco Banerj S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('0','Banco Bankpar S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('740','Banco Barclays S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('107','Banco BBM S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('31','Banco Beg S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('122-8','Banco BERJ S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('739','Banco BGN S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('96','Banco BM&FBOVESPA de Serviços de Liquidação e Custódia S.A');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('318','Banco BMG S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('752','Banco BNP Paribas Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('248','Banco Boavista Interatlântico S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('218','Banco Bonsucesso S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('65','Banco Bracce S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('36','Banco Bradesco BBI S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('204','Banco Bradesco Cartões S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('394','Banco Bradesco Financiamentos S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('237','Banco Bradesco S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('225','Banco Brascan S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M15','Banco BRJ S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('208','Banco BTG Pactual S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('44','Banco BVA S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('263','Banco Cacique S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('473','Banco Caixa Geral - Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('412','Banco Capital S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('40','Banco Cargill S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('266','Banco Cédula S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('233','Banco Cifra S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('745','Banco Citibank S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M08','Banco Citicard S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('241','Banco Clássico S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M19','Banco CNH Capital S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('215','Banco Comercial e de Investimento Sudameris S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('95','Banco Confidence de Câmbio S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('756','Banco Cooperativo do Brasil S.A. - BANCOOB');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('748','Banco Cooperativo Sicredi S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('75','Banco CR2 S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('721','Banco Credibel S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('222','Banco Credit Agricole Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('505','Banco Credit Suisse (Brasil) S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('229','Banco Cruzeiro do Sul S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('3','Banco da Amazônia S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('083-3','Banco da China Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M21','Banco Daimlerchrysler S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('707','Banco Daycoval S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('300','Banco de La Nacion Argentina');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('495','Banco de La Provincia de Buenos Aires');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('494','Banco de La Republica Oriental del Uruguay');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M06','Banco de Lage Landen Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('24','Banco de Pernambuco S.A. - BANDEPE');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('456','Banco de Tokyo-Mitsubishi UFJ Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('214','Banco Dibens S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('1','Banco do Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('47','Banco do Estado de Sergipe S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('37','Banco do Estado do Pará S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('39','Banco do Estado do Piauí S.A. - BEP');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('41','Banco do Estado do Rio Grande do Sul S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('4','Banco do Nordeste do Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('265','Banco Fator S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M03','Banco Fiat S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('224','Banco Fibra S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('626','Banco Ficsa S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('394','Banco Finasa BMC S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M18','Banco Ford S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('734','Banco Gerdau S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M07','Banco GMAC S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('612','Banco Guanabara S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M22','Banco Honda S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('63','Banco Ibi S.A. Banco Múltiplo');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M11','Banco IBM S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('604','Banco Industrial do Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('320','Banco Industrial e Comercial S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('653','Banco Indusval S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('630','Banco Intercap S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('077-9','Banco Intermedium S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('249','Banco Investcred Unibanco S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('184','Banco Itaú BBA S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('479','Banco ItaúBank S.A');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M09','Banco Itaucred Financiamentos S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('376','Banco J. P. Morgan S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('74','Banco J. Safra S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('217','Banco John Deere S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('76','Banco KDB S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('757','Banco KEB do Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('600','Banco Luso Brasileiro S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('243','Banco Máxima S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M12','Banco Maxinvest S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('389','Banco Mercantil do Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('746','Banco Modal S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M10','Banco Moneo S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('738','Banco Morada S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('66','Banco Morgan Stanley S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('45','Banco Opportunity S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('79','Banco Original do Agronegócio S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('212','Banco Original S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M17','Banco Ourinvest S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('623','Banco Panamericano S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('611','Banco Paulista S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('613','Banco Pecúnia S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('094-2','Banco Petra S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('643','Banco Pine S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('724','Banco Porto Seguro S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('735','Banco Pottencial S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('638','Banco Prosper S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M24','Banco PSA Finance Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('747','Banco Rabobank International Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('088-4','Banco Randon S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('356','Banco Real S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('633','Banco Rendimento S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('741','Banco Ribeirão Preto S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M16','Banco Rodobens S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('72','Banco Rural Mais S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('453','Banco Rural S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('422','Banco Safra S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('33','Banco Santander (Brasil) S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('743','Banco Semear S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('749','Banco Simples S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('366','Banco Société Générale Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('637','Banco Sofisa S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('12','Banco Standard de Investimentos S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('464','Banco Sumitomo Mitsui Brasileiro S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('082-5','Banco Topázio S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M20','Banco Toyota do Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('634','Banco Triângulo S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M13','Banco Tricury S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M14','Banco Volkswagen S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('M23','Banco Volvo (Brasil) S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('655','Banco Votorantim S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('610','Banco VR S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('119','Banco Western Union do Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('370','Banco WestLB do Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('21','BANESTES S.A. Banco do Estado do Espírito Santo');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('719','Banif-Banco Internacional do Funchal (Brasil)S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('755','Bank of America Merrill Lynch Banco Múltiplo S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('744','BankBoston N.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('73','BB Banco Popular do Brasil S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('250','BCV - Banco de Crédito e Varejo S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('78','BES Investimento do Brasil S.A.-Banco de Investimento');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('69','BPN Brasil Banco Múltiplo S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('70','BRB - Banco de Brasília S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('092-2','Brickell S.A. Crédito, financiamento e Investimento');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('104','Caixa Econômica Federal');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('114-7','Central das Coop. de Economia e Crédito Mutuo do Est. do ES');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('477','Citibank S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('081-7','Concórdia Banco S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('097-3','Cooperativa Central de Crédito Noroeste Brasileiro Ltda.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('085-x','Cooperativa Central de Crédito Urbano-CECRED');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('099-x','Cooperativa Central de Economia e Credito Mutuo das Unicreds');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('090-2','Cooperativa Central de Economia e Crédito Mutuo das Unicreds');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('089-2','Cooperativa de Crédito Rural da Região de Mogiana');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('087-6','Cooperativa Unicred Central Santa Catarina');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('098-1','Credicorol Cooperativa de Crédito Rural');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('487','Deutsche Bank S.A. - Banco Alemão');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('64','Goldman Sachs do Brasil Banco Múltiplo S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('62','Hipercard Banco Múltiplo S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('399','HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('168','HSBC Finance (Brasil) S.A. - Banco Múltiplo');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('492','ING Bank N.V.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('652','Itaú Unibanco Holding S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('341','Itaú Unibanco S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('488','JPMorgan Chase Bank');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('14','Natixis Brasil S.A. Banco Múltiplo');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('753','NBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('086-8','OBOE Crédito Financiamento e Investimento S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('254','Paraná Banco S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('751','Scotiabank Brasil S.A. Banco Múltiplo');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('409','UNIBANCO - União de Bancos Brasileiros S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('230','Unicard Banco Múltiplo S.A.');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('091-4','Unicred Central do Rio Grande do Sul');
INSERT INTO `lista_bancos` (`id_banco`,`nome`) VALUES ('84','Unicred Norte do Paraná');